
name: Build

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain from rust-toolchain.toml
      run: rustup show
    - name: Install missing targets
      run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
    - name: Test
      run: cargo test --no-fail-fast
    env:
      RUST_BACKTRACE: 1